apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ohdqlr7dy-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ohdqlr7dy-java-quarkus-gitops